### ISSUE TITLE
字打错了

### ISSUE THREAD

**Issue by sbx0** [Geligamesh/foodie-dev#1]
https://github.com/Geligamesh/foodie-dev/blob/f1e7517d9fac6f5c1725a0dd227d2946cc878e47/foodie-pojo/src/main/java/com/gxb/pojo/bo/UserBO.java#L6

又用户传入的数据封装在此 -> 由用户传入的数据封装在此

**Comment by Geligamesh** [comment]
为父知道了

**Comment by sbx0** [comment]
知道了你就把这issue close啊！
